import { LogoElement, CanvasDimensions } from './types';

export interface LogoTemplateItem {
  id: string;
  name: string;
  category: 'Business' | 'Technology' | 'Food' | 'Fashion' | 'Health' | 'Education' | 'Creative' | 'Professional' | 'Industry';
  industry: string;
  description: string;
  tags: string[];
  canvasSize: CanvasDimensions;
  bgType: 'transparent' | 'solid' | 'gradient';
  bgColor: string;
  gradientStart?: string;
  gradientEnd?: string;
  elements: LogoElement[];
}

export const LOGO_TEMPLATES: LogoTemplateItem[] = [
  // 1. TECHNOLOGY / AI
  {
    id: 'tmpl-nexus-ai',
    name: 'Nexus AI Studio',
    category: 'Technology',
    industry: 'Artificial Intelligence & Software',
    description: 'Futuristic hexagon badge with vibrant gradient and geometric typography.',
    tags: ['tech', 'ai', 'hexagon', 'future', 'software', 'chip'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'nexus-hex-outer',
        name: 'Hexagon Frame',
        type: 'shape',
        shapeType: 'hexagon',
        x: 400,
        y: 330,
        width: 240,
        height: 240,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillType: 'linear',
        gradient: { type: 'linear', startColor: '#3b82f6', endColor: '#06b6d4', angle: 45 },
        stroke: { color: '#60a5fa', width: 3 },
      },
      {
        id: 'nexus-icon-cpu',
        name: 'Core Icon',
        type: 'icon',
        iconName: 'Microprocessor Chip',
        iconCategory: 'Technology',
        svgPath: 'M6 4h12v12H6V4zm-2 2H2v2h2v2H2v2h2v2H2v2h2m16-10h2v2h-2v2h2v2h-2v2h2v2h-2M6 2h2v2H6V2zm4 0h2v2h-2V2zm4 0h2v2h-2V2zM6 18h2v4H6v-4zm4 0h2v4h-2v-4zm4 0h2v4h-2v-4z',
        viewBox: '0 0 24 24',
        x: 400,
        y: 330,
        width: 100,
        height: 100,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#ffffff',
      },
      {
        id: 'nexus-title',
        name: 'Brand Title',
        type: 'text',
        text: 'NEXUS',
        fontFamily: 'Outfit, sans-serif',
        fontSize: 64,
        fontWeight: '900',
        letterSpacing: 8,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 530,
        width: 400,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#0f172a',
      },
      {
        id: 'nexus-tagline',
        name: 'Tagline',
        type: 'text',
        text: 'INTELLIGENCE LABS',
        fontFamily: 'Inter, sans-serif',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 6,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 590,
        width: 360,
        height: 30,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        visible: true,
        fillColor: '#3b82f6',
      },
    ],
  },

  // 2. CORPORATE & FINANCE
  {
    id: 'tmpl-vanguard-capital',
    name: 'Vanguard Capital',
    category: 'Business',
    industry: 'Wealth & Asset Management',
    description: 'Distinguished heraldic shield with serif Roman typography.',
    tags: ['finance', 'wealth', 'shield', 'crown', 'legal', 'trust'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'vg-shield',
        name: 'Navy Shield',
        type: 'shape',
        shapeType: 'shield',
        x: 400,
        y: 320,
        width: 220,
        height: 250,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#1e3a8a',
        stroke: { color: '#eab308', width: 4 },
      },
      {
        id: 'vg-crown-icon',
        name: 'Crown Icon',
        type: 'icon',
        iconName: 'Royal Crown',
        iconCategory: 'Business',
        svgPath: 'M2 4l3 12h14l3-12-6 7-4-7-4 7-6-7zm3 14h14v2H5v-2z',
        viewBox: '0 0 24 24',
        x: 400,
        y: 310,
        width: 100,
        height: 100,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#eab308',
      },
      {
        id: 'vg-title',
        name: 'Brand Title',
        type: 'text',
        text: 'VANGUARD',
        fontFamily: 'Cinzel, serif',
        fontSize: 52,
        fontWeight: '800',
        letterSpacing: 6,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 530,
        width: 440,
        height: 60,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#0f172a',
      },
      {
        id: 'vg-tagline',
        name: 'Tagline',
        type: 'text',
        text: 'CAPITAL & WEALTH ADVISORY',
        fontFamily: 'Inter, sans-serif',
        fontSize: 14,
        fontWeight: '600',
        letterSpacing: 4,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 585,
        width: 400,
        height: 30,
        rotation: 0,
        opacity: 0.75,
        locked: false,
        visible: true,
        fillColor: '#475569',
      },
    ],
  },

  // 3. MINIMALIST DESIGN STUDIO
  {
    id: 'tmpl-lumen-studio',
    name: 'Lumen Creative',
    category: 'Creative',
    industry: 'Architecture & Design Atelier',
    description: 'Clean circular geometry with ultra-modern sans typography.',
    tags: ['minimal', 'modern', 'clean', 'circle', 'ring', 'geometry'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'lumen-ring',
        name: 'Concentric Ring',
        type: 'shape',
        shapeType: 'ring',
        x: 400,
        y: 330,
        width: 220,
        height: 220,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#09090b',
        innerRadiusRatio: 0.75,
      },
      {
        id: 'lumen-spark',
        name: 'Diamond Spark',
        type: 'shape',
        shapeType: 'diamond',
        x: 400,
        y: 330,
        width: 70,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#f59e0b',
      },
      {
        id: 'lumen-title',
        name: 'Brand Title',
        type: 'text',
        text: 'L U M E N',
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 54,
        fontWeight: '800',
        letterSpacing: 10,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 525,
        width: 380,
        height: 60,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#09090b',
      },
      {
        id: 'lumen-tagline',
        name: 'Tagline',
        type: 'text',
        text: 'VISUAL DESIGN ATELIER',
        fontFamily: 'Inter, sans-serif',
        fontSize: 13,
        fontWeight: '600',
        letterSpacing: 5,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 575,
        width: 320,
        height: 25,
        rotation: 0,
        opacity: 0.65,
        locked: false,
        visible: true,
        fillColor: '#71717a',
      },
    ],
  },

  // 4. EMBLEM & CRAFT BREW
  {
    id: 'tmpl-heritage-brew',
    name: 'Heritage Brewing Co.',
    category: 'Food',
    industry: 'Craft Brewery & Restaurant',
    description: 'Vintage circular seal badge with curved arch typography.',
    tags: ['vintage', 'badge', 'curved', 'brewery', 'seal', 'coffee', 'heritage'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'hb-badge',
        name: 'Scalloped Badge',
        type: 'shape',
        shapeType: 'badge',
        x: 400,
        y: 400,
        width: 480,
        height: 480,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#291809',
        stroke: { color: '#d97706', width: 6 },
      },
      {
        id: 'hb-inner-circle',
        name: 'Inner Ring',
        type: 'shape',
        shapeType: 'circle',
        x: 400,
        y: 400,
        width: 360,
        height: 360,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: 'transparent',
        stroke: { color: '#fbbf24', width: 2, dash: [8, 6] },
      },
      {
        id: 'hb-curved-title',
        name: 'Curved Top Text',
        type: 'text',
        text: 'HERITAGE BREWING CO',
        fontFamily: 'Cinzel, serif',
        fontSize: 28,
        fontWeight: '900',
        letterSpacing: 4,
        uppercase: true,
        isCurved: true,
        curveRadius: 155,
        curveArc: 170,
        curveDirection: 'convex',
        textAlign: 'center',
        x: 400,
        y: 285,
        width: 360,
        height: 80,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#fbbf24',
      },
      {
        id: 'hb-icon',
        name: 'Flame Icon',
        type: 'icon',
        iconName: 'Grill Fire Flame',
        iconCategory: 'Food',
        svgPath: 'M12 23c-4.97 0-9-4.03-9-9 0-4.92 3.63-8.8 8.16-11.89l.84-.57.84.57C17.37 5.2 21 9.08 21 14c0 4.97-4.03 9-9 9zm0-19.16C8.5 6.74 5 9.94 5 14c0 3.86 3.14 7 7 7s7-3.14 7-7c0-4.06-3.5-7.26-7-10.16z',
        viewBox: '0 0 24 24',
        x: 400,
        y: 400,
        width: 90,
        height: 90,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#d97706',
      },
      {
        id: 'hb-tagline',
        name: 'Year Tag',
        type: 'text',
        text: 'ESTD • 1894',
        fontFamily: 'Oswald, sans-serif',
        fontSize: 20,
        fontWeight: '700',
        letterSpacing: 4,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 495,
        width: 200,
        height: 35,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#fef3c7',
      },
    ],
  },

  // 5. FITNESS & ATHLETICS
  {
    id: 'tmpl-zenith-fitness',
    name: 'Zenith Performance Gym',
    category: 'Industry',
    industry: 'Sports & Athletics',
    description: 'Dynamic chevron angles with fiery energy gradient.',
    tags: ['fitness', 'gym', 'speed', 'bolt', 'energy', 'crossfit'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'zf-chevron',
        name: 'Speed Chevron',
        type: 'shape',
        shapeType: 'chevron',
        x: 400,
        y: 310,
        width: 200,
        height: 180,
        rotation: -90,
        opacity: 1,
        locked: false,
        visible: true,
        fillType: 'linear',
        gradient: { type: 'linear', startColor: '#ef4444', endColor: '#f97316', angle: 90 },
      },
      {
        id: 'zf-bolt-icon',
        name: 'Lightning Bolt',
        type: 'icon',
        iconName: 'High Voltage Bolt',
        iconCategory: 'Fitness',
        svgPath: 'M11 21h-1l1-7H7l7-12h1l-1 7h4l-7 12z',
        viewBox: '0 0 24 24',
        x: 400,
        y: 310,
        width: 80,
        height: 80,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#ffffff',
      },
      {
        id: 'zf-title',
        name: 'Brand Title',
        type: 'text',
        text: 'ZENITH',
        fontFamily: 'Oswald, sans-serif',
        fontSize: 68,
        fontWeight: '900',
        letterSpacing: 6,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 510,
        width: 360,
        height: 75,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#0f172a',
      },
      {
        id: 'zf-tagline',
        name: 'Tagline',
        type: 'text',
        text: 'PERFORMANCE & ATHLETICS',
        fontFamily: 'Inter, sans-serif',
        fontSize: 14,
        fontWeight: '800',
        letterSpacing: 4,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 565,
        width: 360,
        height: 30,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        visible: true,
        fillColor: '#ef4444',
      },
    ],
  },

  // 6. HEALTH & WELLNESS
  {
    id: 'tmpl-solis-wellness',
    name: 'Solis Spa & Wellness',
    category: 'Health',
    industry: 'Holistic Spa & Yoga',
    description: 'Calm organic lotus emblem with serene sage and gold tones.',
    tags: ['spa', 'wellness', 'lotus', 'organic', 'yoga', 'serene'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'sw-circle-bg',
        name: 'Soft Glow Circle',
        type: 'shape',
        shapeType: 'circle',
        x: 400,
        y: 330,
        width: 220,
        height: 220,
        rotation: 0,
        opacity: 0.15,
        locked: false,
        visible: true,
        fillColor: '#15803d',
      },
      {
        id: 'sw-lotus',
        name: 'Lotus Flower',
        type: 'icon',
        iconName: 'Lotus Flower',
        iconCategory: 'Health',
        svgPath: 'M12 4c-1.5 2.5-3 5-3 8 0 2.5 1.5 4 3 4s3-1.5 3-4c0-3-1.5-5.5-3-8zm-4.5 4C6 9.5 4 12 4 14.5c0 2 1.5 3.5 3.5 3.5 1.5 0 2.5-.5 3.5-1.5-1-1.5-1.5-3-1.5-5 0-1.2.5-2.5 2-3.5zm9 0c1.5 1 2 2.3 2 3.5 0 2-.5 3.5-1.5 5 1 1 2 1.5 3.5 1.5 2 0 3.5-1.5 3.5-3.5 0-2.5-2-5-3.5-6.5-1.5-1.5-2.5-2-4-2z',
        viewBox: '0 0 24 24',
        x: 400,
        y: 330,
        width: 120,
        height: 120,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#16a34a',
      },
      {
        id: 'sw-title',
        name: 'Brand Title',
        type: 'text',
        text: 'S O L I S',
        fontFamily: 'Playfair Display, serif',
        fontSize: 52,
        fontWeight: '700',
        letterSpacing: 8,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 520,
        width: 360,
        height: 60,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#052e16',
      },
      {
        id: 'sw-tagline',
        name: 'Tagline',
        type: 'text',
        text: 'HOLISTIC WELLNESS & SPA',
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 13,
        fontWeight: '600',
        letterSpacing: 5,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 570,
        width: 320,
        height: 25,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        visible: true,
        fillColor: '#16a34a',
      },
    ],
  },

  // 7. REAL ESTATE & ARCHITECTURE
  {
    id: 'tmpl-apex-realty',
    name: 'Apex Luxury Estates',
    category: 'Business',
    industry: 'Real Estate & Properties',
    description: 'Modern geometric villa rooflines with sophisticated navy and champagne tones.',
    tags: ['realty', 'home', 'property', 'architecture', 'roof', 'real estate'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'ar-roof',
        name: 'House Structure',
        type: 'icon',
        iconName: 'Modern Home',
        iconCategory: 'Real Estate',
        svgPath: 'M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z',
        viewBox: '0 0 24 24',
        x: 400,
        y: 330,
        width: 140,
        height: 140,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#1e3a8a',
      },
      {
        id: 'ar-title',
        name: 'Brand Title',
        type: 'text',
        text: 'APEX',
        fontFamily: 'Cinzel, serif',
        fontSize: 60,
        fontWeight: '900',
        letterSpacing: 8,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 510,
        width: 380,
        height: 65,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#0f172a',
      },
      {
        id: 'ar-tagline',
        name: 'Tagline',
        type: 'text',
        text: 'ESTATES & RESIDENCES',
        fontFamily: 'Inter, sans-serif',
        fontSize: 14,
        fontWeight: '700',
        letterSpacing: 6,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 565,
        width: 360,
        height: 25,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        visible: true,
        fillColor: '#b45309',
      },
    ],
  },

  // 8. LUXURY FASHION ATELIER
  {
    id: 'tmpl-aura-paris',
    name: 'Aura Haute Couture',
    category: 'Fashion',
    industry: 'Luxury Fashion & Jewelry',
    description: 'High-contrast editorial serif typography with geometric diamond spark.',
    tags: ['fashion', 'luxury', 'jewelry', 'boutique', 'diamond', 'paris'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'aura-gem',
        name: 'Diamond Facet',
        type: 'icon',
        iconName: 'Precious Diamond',
        iconCategory: 'Business',
        svgPath: 'M6 2L2 9l10 13L22 9l-4-7H6zm1.5 2h9l2.7 4.5L12 18.2 4.8 8.5 7.5 4z',
        viewBox: '0 0 24 24',
        x: 400,
        y: 330,
        width: 110,
        height: 110,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#e11d48',
      },
      {
        id: 'aura-title',
        name: 'Brand Title',
        type: 'text',
        text: 'A U R A',
        fontFamily: 'Playfair Display, serif',
        fontSize: 58,
        fontWeight: '900',
        letterSpacing: 12,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 520,
        width: 360,
        height: 65,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#18181b',
      },
      {
        id: 'aura-tagline',
        name: 'Tagline',
        type: 'text',
        text: 'PARIS • GENÈVE',
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 14,
        fontWeight: '600',
        letterSpacing: 6,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 575,
        width: 300,
        height: 25,
        rotation: 0,
        opacity: 0.7,
        locked: false,
        visible: true,
        fillColor: '#881337',
      },
    ],
  },

  // 9. EDUCATION & ACADEMY
  {
    id: 'tmpl-athena-academy',
    name: 'Athena Academy',
    category: 'Education',
    industry: 'Higher Education & Research',
    description: 'Classical neoclassical columns with scholarly laurel badge.',
    tags: ['school', 'college', 'columns', 'law', 'education', 'research'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'aa-columns',
        name: 'Columns Icon',
        type: 'icon',
        iconName: 'Classical Columns',
        iconCategory: 'Real Estate',
        svgPath: 'M2 4h20v2H2V4zm2 3h3v11H4V7zm6 0h4v11h-4V7zm7 0h3v11h-3V7zM2 19h20v2H2v-2z',
        viewBox: '0 0 24 24',
        x: 400,
        y: 330,
        width: 120,
        height: 120,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#1e3a8a',
      },
      {
        id: 'aa-title',
        name: 'Brand Title',
        type: 'text',
        text: 'ATHENA',
        fontFamily: 'Cinzel, serif',
        fontSize: 54,
        fontWeight: '800',
        letterSpacing: 6,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 515,
        width: 360,
        height: 60,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#0f172a',
      },
      {
        id: 'aa-tagline',
        name: 'Tagline',
        type: 'text',
        text: 'INSTITUTE OF SCIENCE',
        fontFamily: 'Inter, sans-serif',
        fontSize: 13,
        fontWeight: '700',
        letterSpacing: 5,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 565,
        width: 340,
        height: 25,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        visible: true,
        fillColor: '#2563eb',
      },
    ],
  },

  // 10. CYBER SECURITY
  {
    id: 'tmpl-cipher-sec',
    name: 'Cipher Security Labs',
    category: 'Technology',
    industry: 'Cybersecurity & Cloud Defense',
    description: 'High-tech lock shield with neon cyber accents.',
    tags: ['security', 'lock', 'shield', 'cloud', 'cyber', 'protect'],
    canvasSize: { width: 800, height: 800 },
    bgType: 'transparent',
    bgColor: '#ffffff',
    elements: [
      {
        id: 'cs-shield',
        name: 'Shield Lock Icon',
        type: 'icon',
        iconName: 'Shield with Padlock',
        iconCategory: 'Security',
        svgPath: 'M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4zm0 10.9c-.8 0-1.5.7-1.5 1.5v2.2c0 .8.7 1.5 1.5 1.5s1.5-.7 1.5-1.5v-2.2c0-.8-.7-1.5-1.5-1.5zm2-3.4V10h-4V8.5C10 7.4 10.9 6.5 12 6.5s2 .9 2 2z',
        viewBox: '0 0 24 24',
        x: 400,
        y: 330,
        width: 130,
        height: 130,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#0284c7',
      },
      {
        id: 'cs-title',
        name: 'Brand Title',
        type: 'text',
        text: 'CIPHER',
        fontFamily: 'Fira Code, monospace',
        fontSize: 54,
        fontWeight: '900',
        letterSpacing: 8,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 520,
        width: 360,
        height: 60,
        rotation: 0,
        opacity: 1,
        locked: false,
        visible: true,
        fillColor: '#0f172a',
      },
      {
        id: 'cs-tagline',
        name: 'Tagline',
        type: 'text',
        text: 'DEFENSE // ZERO TRUST',
        fontFamily: 'Fira Code, monospace',
        fontSize: 13,
        fontWeight: '700',
        letterSpacing: 4,
        uppercase: true,
        textAlign: 'center',
        x: 400,
        y: 570,
        width: 320,
        height: 25,
        rotation: 0,
        opacity: 0.85,
        locked: false,
        visible: true,
        fillColor: '#0284c7',
      },
    ],
  },
];
