import { MaterialPreset, LightingPreset, BevelStyle, ThreeDOptions } from './types';

export interface MaterialDefinition {
  id: MaterialPreset;
  name: string;
  category: 'Metals' | 'Modern' | 'Futuristic' | 'Organic' | 'Reflective';
  previewColor: string;
  faceGradient: { offset: number; color: string }[];
  extrusionColors: { dark: string; mid: string; light: string };
  bevelColor: string;
  bevelShadow: string;
  roughness: number;
  reflectivity: number;
  specular: number;
  ambientLight: number;
}

export const MATERIAL_DEFINITIONS: Record<MaterialPreset, MaterialDefinition> = {
  chrome: {
    id: 'chrome',
    name: 'Mirror Chrome',
    category: 'Metals',
    previewColor: '#94a3b8',
    faceGradient: [
      { offset: 0.0, color: '#ffffff' },
      { offset: 0.2, color: '#e2e8f0' },
      { offset: 0.45, color: '#334155' },
      { offset: 0.5, color: '#0f172a' },
      { offset: 0.55, color: '#64748b' },
      { offset: 0.8, color: '#cbd5e1' },
      { offset: 1.0, color: '#ffffff' },
    ],
    extrusionColors: { dark: '#090d16', mid: '#334155', light: '#94a3b8' },
    bevelColor: '#ffffff',
    bevelShadow: '#020617',
    roughness: 0.1,
    reflectivity: 0.95,
    specular: 0.95,
    ambientLight: 0.35,
  },
  gold: {
    id: 'gold',
    name: '24K Royal Gold',
    category: 'Metals',
    previewColor: '#f59e0b',
    faceGradient: [
      { offset: 0.0, color: '#fef08a' },
      { offset: 0.25, color: '#fbbf24' },
      { offset: 0.5, color: '#d97706' },
      { offset: 0.75, color: '#f59e0b' },
      { offset: 1.0, color: '#fef9c3' },
    ],
    extrusionColors: { dark: '#451a03', mid: '#92400e', light: '#f59e0b' },
    bevelColor: '#fef9c3',
    bevelShadow: '#78350f',
    roughness: 0.2,
    reflectivity: 0.88,
    specular: 0.9,
    ambientLight: 0.4,
  },
  silver: {
    id: 'silver',
    name: 'Platinum Silver',
    category: 'Metals',
    previewColor: '#cbd5e1',
    faceGradient: [
      { offset: 0.0, color: '#ffffff' },
      { offset: 0.3, color: '#e2e8f0' },
      { offset: 0.6, color: '#94a3b8' },
      { offset: 0.85, color: '#cbd5e1' },
      { offset: 1.0, color: '#f8fafc' },
    ],
    extrusionColors: { dark: '#1e293b', mid: '#475569', light: '#cbd5e1' },
    bevelColor: '#ffffff',
    bevelShadow: '#0f172a',
    roughness: 0.25,
    reflectivity: 0.85,
    specular: 0.85,
    ambientLight: 0.45,
  },
  bronze: {
    id: 'bronze',
    name: 'Antique Bronze',
    category: 'Metals',
    previewColor: '#b45309',
    faceGradient: [
      { offset: 0.0, color: '#fed7aa' },
      { offset: 0.3, color: '#ea580c' },
      { offset: 0.6, color: '#9a3412' },
      { offset: 0.85, color: '#c2410c' },
      { offset: 1.0, color: '#ffedd5' },
    ],
    extrusionColors: { dark: '#431407', mid: '#7c2d12', light: '#c2410c' },
    bevelColor: '#fed7aa',
    bevelShadow: '#290b04',
    roughness: 0.35,
    reflectivity: 0.7,
    specular: 0.75,
    ambientLight: 0.4,
  },
  copper: {
    id: 'copper',
    name: 'Polished Copper',
    category: 'Metals',
    previewColor: '#fb923c',
    faceGradient: [
      { offset: 0.0, color: '#ffedd5' },
      { offset: 0.3, color: '#fb923c' },
      { offset: 0.65, color: '#c2410c' },
      { offset: 1.0, color: '#fdba74' },
    ],
    extrusionColors: { dark: '#431407', mid: '#9a3412', light: '#fb923c' },
    bevelColor: '#ffedd5',
    bevelShadow: '#3f1105',
    roughness: 0.28,
    reflectivity: 0.8,
    specular: 0.82,
    ambientLight: 0.4,
  },
  platinum: {
    id: 'platinum',
    name: 'Pure Platinum',
    category: 'Metals',
    previewColor: '#e0e7ff',
    faceGradient: [
      { offset: 0.0, color: '#ffffff' },
      { offset: 0.35, color: '#e0e7ff' },
      { offset: 0.65, color: '#818cf8' },
      { offset: 0.85, color: '#c7d2fe' },
      { offset: 1.0, color: '#ffffff' },
    ],
    extrusionColors: { dark: '#1e1b4b', mid: '#3730a3', light: '#818cf8' },
    bevelColor: '#ffffff',
    bevelShadow: '#0f172a',
    roughness: 0.15,
    reflectivity: 0.92,
    specular: 0.92,
    ambientLight: 0.45,
  },
  metallic: {
    id: 'metallic',
    name: 'Brushed Gunmetal',
    category: 'Metals',
    previewColor: '#64748b',
    faceGradient: [
      { offset: 0.0, color: '#e2e8f0' },
      { offset: 0.3, color: '#94a3b8' },
      { offset: 0.7, color: '#475569' },
      { offset: 1.0, color: '#cbd5e1' },
    ],
    extrusionColors: { dark: '#0f172a', mid: '#1e293b', light: '#64748b' },
    bevelColor: '#f1f5f9',
    bevelShadow: '#020617',
    roughness: 0.4,
    reflectivity: 0.65,
    specular: 0.7,
    ambientLight: 0.4,
  },
  glossy: {
    id: 'glossy',
    name: 'High Gloss Enamel',
    category: 'Modern',
    previewColor: '#3b82f6',
    faceGradient: [
      { offset: 0.0, color: '#93c5fd' },
      { offset: 0.3, color: '#3b82f6' },
      { offset: 0.7, color: '#1d4ed8' },
      { offset: 1.0, color: '#60a5fa' },
    ],
    extrusionColors: { dark: '#172554', mid: '#1e3a8a', light: '#2563eb' },
    bevelColor: '#ffffff',
    bevelShadow: '#0f172a',
    roughness: 0.05,
    reflectivity: 0.9,
    specular: 0.95,
    ambientLight: 0.5,
  },
  matte: {
    id: 'matte',
    name: 'Matte Obsidian',
    category: 'Modern',
    previewColor: '#334155',
    faceGradient: [
      { offset: 0.0, color: '#475569' },
      { offset: 0.5, color: '#334155' },
      { offset: 1.0, color: '#1e293b' },
    ],
    extrusionColors: { dark: '#090d16', mid: '#111827', light: '#1f2937' },
    bevelColor: '#64748b',
    bevelShadow: '#000000',
    roughness: 0.85,
    reflectivity: 0.2,
    specular: 0.25,
    ambientLight: 0.55,
  },
  glass: {
    id: 'glass',
    name: 'Frosted Glass',
    category: 'Reflective',
    previewColor: '#67e8f9',
    faceGradient: [
      { offset: 0.0, color: 'rgba(255, 255, 255, 0.85)' },
      { offset: 0.4, color: 'rgba(165, 243, 252, 0.45)' },
      { offset: 0.8, color: 'rgba(6, 182, 212, 0.35)' },
      { offset: 1.0, color: 'rgba(255, 255, 255, 0.9)' },
    ],
    extrusionColors: { dark: '#083344', mid: '#0e7490', light: '#67e8f9' },
    bevelColor: '#ffffff',
    bevelShadow: '#083344',
    roughness: 0.1,
    reflectivity: 0.9,
    specular: 0.95,
    ambientLight: 0.6,
  },
  crystal: {
    id: 'crystal',
    name: 'Prism Crystal',
    category: 'Reflective',
    previewColor: '#c084fc',
    faceGradient: [
      { offset: 0.0, color: '#fdf4ff' },
      { offset: 0.3, color: '#e879f9' },
      { offset: 0.6, color: '#818cf8' },
      { offset: 0.85, color: '#38bdf8' },
      { offset: 1.0, color: '#ffffff' },
    ],
    extrusionColors: { dark: '#3b0764', mid: '#7e22ce', light: '#c084fc' },
    bevelColor: '#ffffff',
    bevelShadow: '#2e1065',
    roughness: 0.08,
    reflectivity: 0.95,
    specular: 0.98,
    ambientLight: 0.5,
  },
  plastic: {
    id: 'plastic',
    name: 'Vibrant Acrylic',
    category: 'Modern',
    previewColor: '#ef4444',
    faceGradient: [
      { offset: 0.0, color: '#fca5a5' },
      { offset: 0.35, color: '#ef4444' },
      { offset: 0.75, color: '#b91c1c' },
      { offset: 1.0, color: '#f87171' },
    ],
    extrusionColors: { dark: '#450a0a', mid: '#991b1b', light: '#dc2626' },
    bevelColor: '#fee2e2',
    bevelShadow: '#2b0707',
    roughness: 0.25,
    reflectivity: 0.7,
    specular: 0.8,
    ambientLight: 0.45,
  },
  carbon: {
    id: 'carbon',
    name: 'Carbon Fiber Weave',
    category: 'Modern',
    previewColor: '#1e293b',
    faceGradient: [
      { offset: 0.0, color: '#334155' },
      { offset: 0.3, color: '#1e293b' },
      { offset: 0.6, color: '#0f172a' },
      { offset: 0.85, color: '#1e293b' },
      { offset: 1.0, color: '#334155' },
    ],
    extrusionColors: { dark: '#020617', mid: '#0f172a', light: '#334155' },
    bevelColor: '#64748b',
    bevelShadow: '#000000',
    roughness: 0.5,
    reflectivity: 0.4,
    specular: 0.5,
    ambientLight: 0.4,
  },
  steel: {
    id: 'steel',
    name: 'Machined Steel',
    category: 'Metals',
    previewColor: '#94a3b8',
    faceGradient: [
      { offset: 0.0, color: '#f8fafc' },
      { offset: 0.3, color: '#cbd5e1' },
      { offset: 0.55, color: '#64748b' },
      { offset: 0.75, color: '#94a3b8' },
      { offset: 1.0, color: '#e2e8f0' },
    ],
    extrusionColors: { dark: '#1e293b', mid: '#334155', light: '#94a3b8' },
    bevelColor: '#ffffff',
    bevelShadow: '#0f172a',
    roughness: 0.3,
    reflectivity: 0.78,
    specular: 0.82,
    ambientLight: 0.42,
  },
  neon: {
    id: 'neon',
    name: 'Cyberpunk Neon',
    category: 'Futuristic',
    previewColor: '#06b6d4',
    faceGradient: [
      { offset: 0.0, color: '#a5f3fc' },
      { offset: 0.35, color: '#06b6d4' },
      { offset: 0.7, color: '#0284c7' },
      { offset: 1.0, color: '#67e8f9' },
    ],
    extrusionColors: { dark: '#082f49', mid: '#0369a1', light: '#38bdf8' },
    bevelColor: '#ffffff',
    bevelShadow: '#083344',
    roughness: 0.05,
    reflectivity: 0.95,
    specular: 1.0,
    ambientLight: 0.85,
  },
  holographic: {
    id: 'holographic',
    name: 'Rainbow Hologram',
    category: 'Futuristic',
    previewColor: '#ec4899',
    faceGradient: [
      { offset: 0.0, color: '#f43f5e' },
      { offset: 0.2, color: '#eab308' },
      { offset: 0.4, color: '#10b981' },
      { offset: 0.6, color: '#06b6d4' },
      { offset: 0.8, color: '#8b5cf6' },
      { offset: 1.0, color: '#f43f5e' },
    ],
    extrusionColors: { dark: '#31103f', mid: '#6b21a8', light: '#ec4899' },
    bevelColor: '#ffffff',
    bevelShadow: '#1e1b4b',
    roughness: 0.1,
    reflectivity: 0.9,
    specular: 0.95,
    ambientLight: 0.55,
  },
  rubber: {
    id: 'rubber',
    name: 'Soft Touch Matte',
    category: 'Modern',
    previewColor: '#6b7280',
    faceGradient: [
      { offset: 0.0, color: '#9ca3af' },
      { offset: 0.5, color: '#4b5563' },
      { offset: 1.0, color: '#374151' },
    ],
    extrusionColors: { dark: '#111827', mid: '#1f2937', light: '#4b5563' },
    bevelColor: '#9ca3af',
    bevelShadow: '#030712',
    roughness: 0.9,
    reflectivity: 0.15,
    specular: 0.2,
    ambientLight: 0.5,
  },
  ceramic: {
    id: 'ceramic',
    name: 'Glazed Porcelain',
    category: 'Organic',
    previewColor: '#f1f5f9',
    faceGradient: [
      { offset: 0.0, color: '#ffffff' },
      { offset: 0.4, color: '#f8fafc' },
      { offset: 0.75, color: '#e2e8f0' },
      { offset: 1.0, color: '#ffffff' },
    ],
    extrusionColors: { dark: '#334155', mid: '#94a3b8', light: '#e2e8f0' },
    bevelColor: '#ffffff',
    bevelShadow: '#475569',
    roughness: 0.12,
    reflectivity: 0.85,
    specular: 0.9,
    ambientLight: 0.65,
  },
  wood: {
    id: 'wood',
    name: 'Carved Walnut',
    category: 'Organic',
    previewColor: '#854d0e',
    faceGradient: [
      { offset: 0.0, color: '#d97706' },
      { offset: 0.35, color: '#92400e' },
      { offset: 0.75, color: '#78350f' },
      { offset: 1.0, color: '#b45309' },
    ],
    extrusionColors: { dark: '#270e04', mid: '#451a03', light: '#78350f' },
    bevelColor: '#fde68a',
    bevelShadow: '#1a0802',
    roughness: 0.65,
    reflectivity: 0.3,
    specular: 0.35,
    ambientLight: 0.45,
  },
  stone: {
    id: 'stone',
    name: 'Chiseled Granite',
    category: 'Organic',
    previewColor: '#52525b',
    faceGradient: [
      { offset: 0.0, color: '#a1a1aa' },
      { offset: 0.4, color: '#71717a' },
      { offset: 0.8, color: '#3f3f46' },
      { offset: 1.0, color: '#71717a' },
    ],
    extrusionColors: { dark: '#18181b', mid: '#27272a', light: '#52525b' },
    bevelColor: '#d4d4d8',
    bevelShadow: '#09090b',
    roughness: 0.75,
    reflectivity: 0.25,
    specular: 0.3,
    ambientLight: 0.4,
  },
  'liquid-metal': {
    id: 'liquid-metal',
    name: 'Quicksilver Liquid',
    category: 'Futuristic',
    previewColor: '#a855f7',
    faceGradient: [
      { offset: 0.0, color: '#ffffff' },
      { offset: 0.25, color: '#d8b4fe' },
      { offset: 0.5, color: '#4c1d95' },
      { offset: 0.6, color: '#7c3aed' },
      { offset: 0.85, color: '#c084fc' },
      { offset: 1.0, color: '#ffffff' },
    ],
    extrusionColors: { dark: '#1e1b4b', mid: '#581c87', light: '#a855f7' },
    bevelColor: '#ffffff',
    bevelShadow: '#1e1035',
    roughness: 0.08,
    reflectivity: 0.96,
    specular: 0.98,
    ambientLight: 0.4,
  },
};

export const LIGHTING_DEFINITIONS: Record<LightingPreset, {
  id: LightingPreset;
  name: string;
  angle: number;
  elevation: number;
  intensity: number;
  ambient: number;
  specular: number;
  description: string;
}> = {
  'soft-studio': {
    id: 'soft-studio',
    name: 'Soft Studio',
    angle: 315,
    elevation: 45,
    intensity: 1.0,
    ambient: 0.45,
    specular: 0.65,
    description: 'Balanced studio diffused key light',
  },
  'hard-studio': {
    id: 'hard-studio',
    name: 'Hard Studio',
    angle: 300,
    elevation: 60,
    intensity: 1.4,
    ambient: 0.25,
    specular: 0.95,
    description: 'Crisp high-contrast key and specular specular glints',
  },
  'top-light': {
    id: 'top-light',
    name: 'Top Downlight',
    angle: 270,
    elevation: 75,
    intensity: 1.2,
    ambient: 0.35,
    specular: 0.8,
    description: 'Dramatic overhead stage downlighting',
  },
  'front-light': {
    id: 'front-light',
    name: 'Front Key',
    angle: 0,
    elevation: 85,
    intensity: 1.1,
    ambient: 0.5,
    specular: 0.7,
    description: 'Direct straight-on illuminated face',
  },
  'side-light': {
    id: 'side-light',
    name: 'Side Edge Light',
    angle: 180,
    elevation: 30,
    intensity: 1.3,
    ambient: 0.3,
    specular: 0.9,
    description: 'Strong lateral rake revealing 3D extrusion sides',
  },
  'rim-light': {
    id: 'rim-light',
    name: 'Rim Contour',
    angle: 135,
    elevation: 25,
    intensity: 1.5,
    ambient: 0.2,
    specular: 1.0,
    description: 'Sharp silhouette rim highlight on edges',
  },
  dramatic: {
    id: 'dramatic',
    name: 'Dramatic Chiaroscuro',
    angle: 225,
    elevation: 35,
    intensity: 1.6,
    ambient: 0.15,
    specular: 0.95,
    description: 'Deep shadows with intense focused beam',
  },
  cinematic: {
    id: 'cinematic',
    name: 'Cinematic Anamorphic',
    angle: 330,
    elevation: 50,
    intensity: 1.25,
    ambient: 0.38,
    specular: 0.85,
    description: 'Warm gold and cool blue theatrical balance',
  },
  neon: {
    id: 'neon',
    name: 'Cyber Neon Glow',
    angle: 290,
    elevation: 40,
    intensity: 1.7,
    ambient: 0.6,
    specular: 1.0,
    description: 'Ultra vibrant emission with electric speculars',
  },
  ambient: {
    id: 'ambient',
    name: 'Soft Ambient Flat',
    angle: 0,
    elevation: 90,
    intensity: 0.85,
    ambient: 0.75,
    specular: 0.3,
    description: 'Uniform omni-directional soft illumination',
  },
  'glossy-product': {
    id: 'glossy-product',
    name: 'Glossy Showcase',
    angle: 310,
    elevation: 55,
    intensity: 1.3,
    ambient: 0.4,
    specular: 0.92,
    description: 'Dual light-box reflections for luxury goods',
  },
  metallic: {
    id: 'metallic',
    name: 'Metallic Sheen',
    angle: 45,
    elevation: 45,
    intensity: 1.45,
    ambient: 0.3,
    specular: 0.98,
    description: 'Dynamic gradient sweep highlights on curved surfaces',
  },
};

export const BEVEL_DEFINITIONS: Record<BevelStyle, {
  name: string;
  size: number;
  highlightIntensity: number;
  description: string;
}> = {
  soft: { name: 'Soft Curve', size: 4, highlightIntensity: 0.6, description: 'Gently rounded edge' },
  sharp: { name: 'Razor Sharp', size: 2, highlightIntensity: 1.0, description: 'Crisp machined chamfer' },
  rounded: { name: 'Pillow Round', size: 6, highlightIntensity: 0.7, description: 'Generous radius contour' },
  cut: { name: 'Facet Cut', size: 5, highlightIntensity: 0.9, description: 'Chiseled angular bevel' },
  deep: { name: 'Deep Chamfer', size: 8, highlightIntensity: 0.85, description: 'Heavy sculptural bevel' },
  minimal: { name: 'Micro Bevel', size: 1.5, highlightIntensity: 0.45, description: 'Subtle clean edge definition' },
};

export const LIGHTING_PRESETS = LIGHTING_DEFINITIONS;
export const BEVEL_STYLES = BEVEL_DEFINITIONS;

export interface ThreeDLogoPreset {
  id: string;
  name: string;
  category: string;
  material: MaterialPreset;
  depth: number;
  perspective: number;
  rotX: number;
  rotY: number;
  rotZ: number;
  lightingPreset: LightingPreset;
  bevelStyle: BevelStyle;
  bevelSize: number;
  shadowType: 'drop' | 'extrusion' | 'long' | 'directional' | 'soft' | 'none';
  shadowBlur: number;
  shadowOpacity: number;
  shadowDistance: number;
  sampleText: string;
  sampleFont: string;
  iconName: string;
  tagline: string;
  description: string;
}

export const THREE_D_LOGO_PRESETS: ThreeDLogoPreset[] = [
  {
    id: '3d-preset-gold',
    name: '3D Royal Gold Master',
    category: 'Luxury',
    material: 'gold',
    depth: 32,
    perspective: 0.35,
    rotX: 12,
    rotY: -14,
    rotZ: 0,
    lightingPreset: 'metallic',
    bevelStyle: 'cut',
    bevelSize: 4,
    shadowType: 'extrusion',
    shadowBlur: 24,
    shadowOpacity: 0.65,
    shadowDistance: 26,
    sampleText: 'AUREUS',
    sampleFont: 'Cinzel, serif',
    iconName: 'Crown',
    tagline: 'LUXURY HERITAGE',
    description: 'Opulent 24K gold with chiseled facets and deep extrusion shadow',
  },
  {
    id: '3d-preset-chrome',
    name: '3D Automotive Chrome',
    category: 'Automotive',
    material: 'chrome',
    depth: 36,
    perspective: 0.4,
    rotX: 15,
    rotY: -18,
    rotZ: 0,
    lightingPreset: 'hard-studio',
    bevelStyle: 'sharp',
    bevelSize: 3,
    shadowType: 'directional',
    shadowBlur: 18,
    shadowOpacity: 0.75,
    shadowDistance: 28,
    sampleText: 'APEX',
    sampleFont: 'Montserrat, sans-serif',
    iconName: 'Shield',
    tagline: 'PRECISION MOTORWORKS',
    description: 'High-gloss mirror chrome with sharp machined chamfers',
  },
  {
    id: '3d-preset-cyber-neon',
    name: '3D Cyber Neon Pulse',
    category: 'Gaming & Tech',
    material: 'neon',
    depth: 40,
    perspective: 0.45,
    rotX: 18,
    rotY: -20,
    rotZ: 0,
    lightingPreset: 'neon',
    bevelStyle: 'sharp',
    bevelSize: 3,
    shadowType: 'soft',
    shadowBlur: 35,
    shadowOpacity: 0.85,
    shadowDistance: 20,
    sampleText: 'NEXUS',
    sampleFont: 'Orbitron, sans-serif',
    iconName: 'Zap',
    tagline: 'FUTURE ENGINE',
    description: 'Electrifying cyan emission with vibrant ambient bloom',
  },
  {
    id: '3d-preset-liquid-metal',
    name: '3D Liquid Quicksilver',
    category: 'Futuristic',
    material: 'liquid-metal',
    depth: 30,
    perspective: 0.35,
    rotX: 10,
    rotY: -15,
    rotZ: 0,
    lightingPreset: 'cinematic',
    bevelStyle: 'rounded',
    bevelSize: 5,
    shadowType: 'extrusion',
    shadowBlur: 22,
    shadowOpacity: 0.7,
    shadowDistance: 24,
    sampleText: 'SYNTH',
    sampleFont: 'Space Grotesk, sans-serif',
    iconName: 'Atom',
    tagline: 'NEURAL LABS',
    description: 'Flowing violet-chrome fluid specular reflections',
  },
  {
    id: '3d-preset-frosted-glass',
    name: '3D Frosted Crystal Glass',
    category: 'Modern',
    material: 'glass',
    depth: 25,
    perspective: 0.3,
    rotX: 8,
    rotY: -12,
    rotZ: 0,
    lightingPreset: 'glossy-product',
    bevelStyle: 'soft',
    bevelSize: 4,
    shadowType: 'soft',
    shadowBlur: 30,
    shadowOpacity: 0.4,
    shadowDistance: 20,
    sampleText: 'LUMEN',
    sampleFont: 'Outfit, sans-serif',
    iconName: 'Sparkles',
    tagline: 'STUDIO ARCHITECTURE',
    description: 'Refractive frosted acrylic with crisp perimeter edge glare',
  },
  {
    id: '3d-preset-titanium-carbon',
    name: '3D Carbon & Titanium',
    category: 'Industrial',
    material: 'carbon',
    depth: 28,
    perspective: 0.35,
    rotX: 14,
    rotY: -14,
    rotZ: 0,
    lightingPreset: 'rim-light',
    bevelStyle: 'sharp',
    bevelSize: 2,
    shadowType: 'extrusion',
    shadowBlur: 16,
    shadowOpacity: 0.8,
    shadowDistance: 22,
    sampleText: 'TITAN',
    sampleFont: 'Oswald, sans-serif',
    iconName: 'Hexagon',
    tagline: 'AEROSPACE DYNAMICS',
    description: 'Stealth weave carbon composite with silver rim contour',
  },
  {
    id: '3d-preset-antique-bronze',
    name: '3D Bronze Crest',
    category: 'Heritage',
    material: 'bronze',
    depth: 34,
    perspective: 0.3,
    rotX: 12,
    rotY: -10,
    rotZ: 0,
    lightingPreset: 'dramatic',
    bevelStyle: 'deep',
    bevelSize: 6,
    shadowType: 'long',
    shadowBlur: 20,
    shadowOpacity: 0.7,
    shadowDistance: 32,
    sampleText: 'VALOR',
    sampleFont: 'Playfair Display, serif',
    iconName: 'Shield',
    tagline: 'ESTABLISHED 1894',
    description: 'Sculpted antique bronze medal with deep hand-carved relief',
  },
  {
    id: '3d-preset-pure-platinum',
    name: '3D Pure Platinum Monogram',
    category: 'Luxury',
    material: 'platinum',
    depth: 26,
    perspective: 0.25,
    rotX: 8,
    rotY: -10,
    rotZ: 0,
    lightingPreset: 'soft-studio',
    bevelStyle: 'cut',
    bevelSize: 3,
    shadowType: 'directional',
    shadowBlur: 18,
    shadowOpacity: 0.55,
    shadowDistance: 20,
    sampleText: 'ELITE',
    sampleFont: 'Cinzel, serif',
    iconName: 'Diamond',
    tagline: 'HAUTE COUTURE',
    description: 'Bright ice-white platinum sheen with diamond facet cuts',
  },
  {
    id: '3d-preset-gaming-sports',
    name: '3D Gaming Arena Impact',
    category: 'Gaming & Sports',
    material: 'plastic',
    depth: 42,
    perspective: 0.45,
    rotX: 20,
    rotY: -22,
    rotZ: 0,
    lightingPreset: 'hard-studio',
    bevelStyle: 'sharp',
    bevelSize: 4,
    shadowType: 'long',
    shadowBlur: 26,
    shadowOpacity: 0.8,
    shadowDistance: 38,
    sampleText: 'VORTEX',
    sampleFont: 'Russo One, sans-serif',
    iconName: 'Flame',
    tagline: 'ESPORTS ESPORTS LEAGUE',
    description: 'Heavy angled athletic 3D block text with deep red cast shadow',
  },
  {
    id: '3d-preset-minimal-steel',
    name: '3D Minimal Brushed Steel',
    category: 'Corporate',
    material: 'steel',
    depth: 18,
    perspective: 0.2,
    rotX: 6,
    rotY: -8,
    rotZ: 0,
    lightingPreset: 'front-light',
    bevelStyle: 'minimal',
    bevelSize: 1.5,
    shadowType: 'drop',
    shadowBlur: 12,
    shadowOpacity: 0.45,
    shadowDistance: 14,
    sampleText: 'PRISM',
    sampleFont: 'Inter, sans-serif',
    iconName: 'Layers',
    tagline: 'FINANCIAL CAPITAL',
    description: 'Clean architectural slab lettering with subtle dimensional extrusion',
  },
  {
    id: '3d-preset-carved-wood',
    name: '3D Artisan Walnut',
    category: 'Craft & Organic',
    material: 'wood',
    depth: 30,
    perspective: 0.3,
    rotX: 10,
    rotY: -12,
    rotZ: 0,
    lightingPreset: 'dramatic',
    bevelStyle: 'rounded',
    bevelSize: 5,
    shadowType: 'extrusion',
    shadowBlur: 18,
    shadowOpacity: 0.65,
    shadowDistance: 22,
    sampleText: 'TIMBER',
    sampleFont: 'Merriweather, serif',
    iconName: 'Leaf',
    tagline: 'HANDCRAFTED SPIRITS',
    description: 'Warm organic grain tones with sculpted relief edges',
  },
  {
    id: '3d-preset-prism-crystal',
    name: '3D Rainbow Prism Crystal',
    category: 'Creative',
    material: 'crystal',
    depth: 32,
    perspective: 0.38,
    rotX: 14,
    rotY: -16,
    rotZ: 0,
    lightingPreset: 'cinematic',
    bevelStyle: 'cut',
    bevelSize: 4.5,
    shadowType: 'soft',
    shadowBlur: 28,
    shadowOpacity: 0.6,
    shadowDistance: 26,
    sampleText: 'KALEIDO',
    sampleFont: 'Outfit, sans-serif',
    iconName: 'Star',
    tagline: 'CREATIVE AGENCY',
    description: 'Prismatic multi-spectral refraction with high-gloss highlights',
  },
];

export function createDefaultThreeDOptions(overrides?: Partial<ThreeDOptions>): ThreeDOptions {
  return {
    enabled: true,
    depth: 28,
    perspective: 0.35,
    rotX: 12,
    rotY: -14,
    rotZ: 0,
    lightAngle: 315,
    lightElevation: 45,
    lightIntensity: 1.2,
    ambientLight: 0.4,
    specular: 0.85,
    material: 'gold',
    roughness: 0.2,
    reflectivity: 0.85,
    bevelSize: 3,
    bevelStyle: 'sharp',
    shadowType: 'extrusion',
    shadowAngle: 315,
    shadowDistance: 24,
    shadowBlur: 20,
    shadowOpacity: 0.6,
    shadowColor: '#000000',
    lightingPreset: 'metallic',
    ...overrides,
  };
}
