import { DocumentPreset, UnitType } from './types';

export const DOCUMENT_PRESETS: DocumentPreset[] = [
  // Social Media
  {
    id: 'instagram-post',
    name: 'Instagram Post (Square)',
    category: 'Social',
    width: 1080,
    height: 1080,
    unit: 'px',
    dpi: 72,
    description: 'Standard 1:1 square post feed',
    aspectRatio: '1:1',
  },
  {
    id: 'instagram-portrait',
    name: 'Instagram Post (Portrait)',
    category: 'Social',
    width: 1080,
    height: 1350,
    unit: 'px',
    dpi: 72,
    description: 'Vertical 4:5 expanded feed post',
    aspectRatio: '4:5',
  },
  {
    id: 'instagram-story',
    name: 'Instagram Story / Reel',
    category: 'Social',
    width: 1080,
    height: 1920,
    unit: 'px',
    dpi: 72,
    description: 'Full vertical 9:16 mobile canvas',
    aspectRatio: '9:16',
  },
  {
    id: 'youtube-thumbnail',
    name: 'YouTube Thumbnail',
    category: 'Social',
    width: 1280,
    height: 720,
    unit: 'px',
    dpi: 72,
    description: '16:9 high click-through video banner',
    aspectRatio: '16:9',
  },
  {
    id: 'youtube-banner',
    name: 'YouTube Channel Banner',
    category: 'Social',
    width: 2560,
    height: 1440,
    unit: 'px',
    dpi: 72,
    description: 'TV & multi-device channel art',
    aspectRatio: '16:9',
  },
  {
    id: 'facebook-post',
    name: 'Facebook Post',
    category: 'Social',
    width: 1200,
    height: 630,
    unit: 'px',
    dpi: 72,
    description: 'Landscape post with open-graph preview',
    aspectRatio: '1.91:1',
  },
  {
    id: 'facebook-cover',
    name: 'Facebook Page Cover',
    category: 'Social',
    width: 820,
    height: 312,
    unit: 'px',
    dpi: 72,
    description: 'Desktop header with mobile safe zone',
    aspectRatio: '2.6:1',
  },
  {
    id: 'linkedin-post',
    name: 'LinkedIn Feed Post',
    category: 'Social',
    width: 1200,
    height: 627,
    unit: 'px',
    dpi: 72,
    description: 'Professional landscape business creative',
    aspectRatio: '1.91:1',
  },
  {
    id: 'linkedin-banner',
    name: 'LinkedIn Background Banner',
    category: 'Social',
    width: 1584,
    height: 396,
    unit: 'px',
    dpi: 72,
    description: 'Profile 4:1 executive header',
    aspectRatio: '4:1',
  },
  {
    id: 'pinterest-pin',
    name: 'Pinterest Pin',
    category: 'Social',
    width: 1000,
    height: 1500,
    unit: 'px',
    dpi: 72,
    description: 'Vertical 2:3 high-discovery pin',
    aspectRatio: '2:3',
  },
  {
    id: 'x-twitter-post',
    name: 'X / Twitter Post',
    category: 'Social',
    width: 1200,
    height: 675,
    unit: 'px',
    dpi: 72,
    description: '16:9 social share photo card',
    aspectRatio: '16:9',
  },
  {
    id: 'tiktok-cover',
    name: 'TikTok Video Cover',
    category: 'Social',
    width: 1080,
    height: 1920,
    unit: 'px',
    dpi: 72,
    description: 'Full vertical mobile cover frame',
    aspectRatio: '9:16',
  },

  // Print Formats
  {
    id: 'print-a4',
    name: 'A4 Document',
    category: 'Print',
    width: 2480,
    height: 3508,
    unit: 'px',
    dpi: 300,
    description: '210 x 297 mm international standard',
    aspectRatio: '1:1.41',
  },
  {
    id: 'print-a3',
    name: 'A3 Poster',
    category: 'Print',
    width: 3508,
    height: 4960,
    unit: 'px',
    dpi: 300,
    description: '297 x 420 mm display poster',
    aspectRatio: '1:1.41',
  },
  {
    id: 'print-a5',
    name: 'A5 Booklet / Flyer',
    category: 'Print',
    width: 1748,
    height: 2480,
    unit: 'px',
    dpi: 300,
    description: '148 x 210 mm compact handout',
    aspectRatio: '1:1.41',
  },
  {
    id: 'print-letter',
    name: 'US Letter',
    category: 'Print',
    width: 2550,
    height: 3300,
    unit: 'px',
    dpi: 300,
    description: '8.5 x 11 in standard office document',
    aspectRatio: '1:1.29',
  },
  {
    id: 'print-legal',
    name: 'US Legal',
    category: 'Print',
    width: 2550,
    height: 4200,
    unit: 'px',
    dpi: 300,
    description: '8.5 x 14 in legal contract format',
    aspectRatio: '1:1.65',
  },
  {
    id: 'print-poster',
    name: 'Wall Poster (18x24 in)',
    category: 'Print',
    width: 1800,
    height: 2400,
    unit: 'px',
    dpi: 300,
    description: 'Standard gallery medium wall poster',
    aspectRatio: '3:4',
  },
  {
    id: 'print-flyer',
    name: 'Marketing Flyer',
    category: 'Print',
    width: 1200,
    height: 1800,
    unit: 'px',
    dpi: 300,
    description: 'Event or product marketing flyer',
    aspectRatio: '2:3',
  },
  {
    id: 'print-business-card',
    name: 'Business Card (3.5x2 in)',
    category: 'Print',
    width: 1050,
    height: 600,
    unit: 'px',
    dpi: 300,
    description: 'Standard horizontal business card with bleed',
    aspectRatio: '1.75:1',
  },
  {
    id: 'print-certificate',
    name: 'Award Certificate',
    category: 'Print',
    width: 1920,
    height: 1080,
    unit: 'px',
    dpi: 300,
    description: 'Landscape formal diploma or recognition',
    aspectRatio: '16:9',
  },
  {
    id: 'print-invitation',
    name: 'Event Invitation',
    category: 'Print',
    width: 1500,
    height: 2100,
    unit: 'px',
    dpi: 300,
    description: '5x7 in celebration & gala invitation',
    aspectRatio: '5:7',
  },

  // Digital & Web
  {
    id: 'digital-presentation',
    name: 'Presentation (16:9)',
    category: 'Digital',
    width: 1920,
    height: 1080,
    unit: 'px',
    dpi: 72,
    description: 'Full HD slide presentation display',
    aspectRatio: '16:9',
  },
  {
    id: 'digital-hero',
    name: 'Website Hero Section',
    category: 'Digital',
    width: 1920,
    height: 800,
    unit: 'px',
    dpi: 72,
    description: 'Homepage wide header showcase',
    aspectRatio: '2.4:1',
  },
  {
    id: 'digital-banner',
    name: 'Web Billboard Banner',
    category: 'Digital',
    width: 1200,
    height: 600,
    unit: 'px',
    dpi: 72,
    description: 'High-impact 2:1 advertising banner',
    aspectRatio: '2:1',
  },
  {
    id: 'digital-blog',
    name: 'Blog Post Header',
    category: 'Digital',
    width: 1200,
    height: 630,
    unit: 'px',
    dpi: 72,
    description: 'Editorial article cover graphic',
    aspectRatio: '1.91:1',
  },
  {
    id: 'digital-email',
    name: 'Email Newsletter Banner',
    category: 'Digital',
    width: 600,
    height: 300,
    unit: 'px',
    dpi: 72,
    description: 'Clean responsive 2:1 newsletter header',
    aspectRatio: '2:1',
  },
  {
    id: 'digital-ad-square',
    name: 'Display Ad (1:1 Square)',
    category: 'Digital',
    width: 1080,
    height: 1080,
    unit: 'px',
    dpi: 72,
    description: 'Universal programmatic marketing creative',
    aspectRatio: '1:1',
  },
];

export function convertToPixels(value: number, unit: UnitType, dpi: number = 72): number {
  switch (unit) {
    case 'in':
      return Math.round(value * dpi);
    case 'cm':
      return Math.round((value / 2.54) * dpi);
    case 'mm':
      return Math.round((value / 25.4) * dpi);
    case 'px':
    default:
      return Math.round(value);
  }
}

export function convertFromPixels(pixels: number, targetUnit: UnitType, dpi: number = 72): number {
  switch (targetUnit) {
    case 'in':
      return Number((pixels / dpi).toFixed(2));
    case 'cm':
      return Number(((pixels / dpi) * 2.54).toFixed(2));
    case 'mm':
      return Number(((pixels / dpi) * 25.4).toFixed(1));
    case 'px':
    default:
      return Math.round(pixels);
  }
}
