import { DesignElement, CanvasSettings } from './types';

export interface DesignTemplate {
  id: string;
  name: string;
  category: 'Social' | 'Marketing' | 'Business' | 'Events' | 'Creative';
  thumbnailColor: string;
  canvas: {
    width: number;
    height: number;
    bgType: CanvasSettings['bgType'];
    bgColor: string;
    gradientStart: string;
    gradientEnd: string;
    gradientAngle: number;
  };
  elements: DesignElement[];
}

export const DESIGN_TEMPLATES: DesignTemplate[] = [
  {
    id: 'cyber-launch-post',
    name: 'Tech Product Launch Post',
    category: 'Social',
    thumbnailColor: '#0f172a',
    canvas: {
      width: 1080,
      height: 1080,
      bgType: 'gradient',
      bgColor: '#090d16',
      gradientStart: '#090d16',
      gradientEnd: '#1e1b4b',
      gradientAngle: 145,
    },
    elements: [
      {
        id: 'tpl-1-glow',
        name: 'Ambient Neon Glow',
        type: 'shape',
        shapeType: 'circle',
        x: 190,
        y: 190,
        width: 700,
        height: 700,
        rotation: 0,
        opacity: 0.25,
        visible: true,
        locked: false,
        zIndex: 1,
        blendMode: 'screen',
        fillColor: '#6366f1',
      },
      {
        id: 'tpl-1-tag',
        name: 'Category Pill',
        type: 'text',
        x: 100,
        y: 120,
        width: 320,
        height: 48,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2,
        blendMode: 'normal',
        text: 'NEXT-GEN AI WORKSPACE',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        textColor: '#38bdf8',
        textTransform: 'uppercase',
        letterSpacing: 0.12,
        textBackground: {
          enabled: true,
          color: 'rgba(56, 189, 248, 0.12)',
          padding: 8,
          radius: 999,
        },
      },
      {
        id: 'tpl-1-heading',
        name: 'Main Headline',
        type: 'text',
        x: 100,
        y: 200,
        width: 880,
        height: 180,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3,
        blendMode: 'normal',
        text: 'Build Smarter.\nCreate Faster.',
        fontFamily: 'system-ui, -apple-system, sans-serif',
        fontSize: 72,
        fontWeight: '900',
        textAlign: 'left',
        textColor: '#ffffff',
        lineHeight: 1.1,
        shadow: {
          color: '#000000',
          blur: 18,
          offsetX: 0,
          offsetY: 6,
          opacity: 0.5,
        },
      },
      {
        id: 'tpl-1-sub',
        name: 'Subtitle Description',
        type: 'text',
        x: 100,
        y: 400,
        width: 780,
        height: 80,
        rotation: 0,
        opacity: 0.85,
        visible: true,
        locked: false,
        zIndex: 4,
        blendMode: 'normal',
        text: 'Transform your creative workflow with automated visual intelligence, high-precision typography, and instant multi-format vector exports.',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 22,
        fontWeight: '400',
        textAlign: 'left',
        textColor: '#94a3b8',
        lineHeight: 1.4,
      },
      {
        id: 'tpl-1-card',
        name: 'Feature Card Box',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 100,
        y: 530,
        width: 880,
        height: 380,
        rotation: 0,
        opacity: 0.9,
        visible: true,
        locked: false,
        zIndex: 5,
        blendMode: 'normal',
        fillColor: '#1e293b',
        strokeColor: '#334155',
        strokeWidth: 2,
        cornerRadius: 24,
        shadow: {
          color: '#000000',
          blur: 30,
          offsetX: 0,
          offsetY: 15,
          opacity: 0.4,
        },
      },
      {
        id: 'tpl-1-cta-btn',
        name: 'Call To Action Pill',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 150,
        y: 790,
        width: 260,
        height: 64,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 6,
        blendMode: 'normal',
        fillColor: '#3b82f6',
        cornerRadius: 16,
      },
      {
        id: 'tpl-1-cta-text',
        name: 'CTA Button Text',
        type: 'text',
        x: 150,
        y: 806,
        width: 260,
        height: 32,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 7,
        blendMode: 'normal',
        text: 'Explore Platform →',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 20,
        fontWeight: '700',
        textAlign: 'center',
        textColor: '#ffffff',
      },
    ],
  },
  {
    id: 'yt-thumbnail-master',
    name: 'Viral YouTube Thumbnail',
    category: 'Social',
    thumbnailColor: '#dc2626',
    canvas: {
      width: 1280,
      height: 720,
      bgType: 'gradient',
      bgColor: '#000000',
      gradientStart: '#0f172a',
      gradientEnd: '#450a0a',
      gradientAngle: 135,
    },
    elements: [
      {
        id: 'tpl-2-badge',
        name: 'Shock Badge Pill',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 80,
        y: 80,
        width: 280,
        height: 56,
        rotation: -4,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1,
        blendMode: 'normal',
        fillColor: '#e11d48',
        cornerRadius: 12,
      },
      {
        id: 'tpl-2-badgetxt',
        name: 'Shock Badge Text',
        type: 'text',
        x: 80,
        y: 92,
        width: 280,
        height: 36,
        rotation: -4,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2,
        blendMode: 'normal',
        text: 'NEW WORKFLOW 2026',
        fontFamily: 'Impact, sans-serif',
        fontSize: 24,
        fontWeight: '900',
        textAlign: 'center',
        textColor: '#ffffff',
        letterSpacing: 0.05,
      },
      {
        id: 'tpl-2-maintext',
        name: 'Massive Thumbnail Text',
        type: 'text',
        x: 70,
        y: 180,
        width: 720,
        height: 240,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3,
        blendMode: 'normal',
        text: 'NEVER USE\nOLD TOOLS!',
        fontFamily: 'Impact, sans-serif',
        fontSize: 96,
        fontWeight: '900',
        textAlign: 'left',
        textColor: '#facc15',
        lineHeight: 1.0,
        textOutline: {
          color: '#000000',
          width: 8,
        },
        shadow: {
          color: '#000000',
          blur: 24,
          offsetX: 6,
          offsetY: 8,
          opacity: 0.8,
        },
      },
      {
        id: 'tpl-2-sub',
        name: 'Highlight Pill',
        type: 'text',
        x: 80,
        y: 470,
        width: 460,
        height: 80,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4,
        blendMode: 'normal',
        text: '10X FASTER OUTPUT',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 36,
        fontWeight: '900',
        textAlign: 'center',
        textColor: '#ffffff',
        textBackground: {
          enabled: true,
          color: '#2563eb',
          padding: 12,
          radius: 12,
        },
      },
      {
        id: 'tpl-2-shield',
        name: 'Icon Graphic Badge',
        type: 'shape',
        shapeType: 'star',
        x: 880,
        y: 180,
        width: 320,
        height: 320,
        rotation: 12,
        opacity: 0.95,
        visible: true,
        locked: false,
        zIndex: 5,
        blendMode: 'normal',
        fillColor: '#f59e0b',
        strokeColor: '#ffffff',
        strokeWidth: 6,
      },
    ],
  },
  {
    id: 'luxury-fashion-banner',
    name: 'Luxury Brand Campaign',
    category: 'Marketing',
    thumbnailColor: '#1c1917',
    canvas: {
      width: 1200,
      height: 630,
      bgType: 'solid',
      bgColor: '#0c0a09',
      gradientStart: '#0c0a09',
      gradientEnd: '#292524',
      gradientAngle: 90,
    },
    elements: [
      {
        id: 'tpl-3-border',
        name: 'Editorial Inset Frame',
        type: 'shape',
        shapeType: 'rect',
        x: 40,
        y: 40,
        width: 1120,
        height: 550,
        rotation: 0,
        opacity: 0.4,
        visible: true,
        locked: false,
        zIndex: 1,
        blendMode: 'normal',
        fillColor: 'transparent',
        strokeColor: '#d6d3d1',
        strokeWidth: 1,
      },
      {
        id: 'tpl-3-season',
        name: 'Season Eyebrow',
        type: 'text',
        x: 100,
        y: 140,
        width: 1000,
        height: 30,
        rotation: 0,
        opacity: 0.75,
        visible: true,
        locked: false,
        zIndex: 2,
        blendMode: 'normal',
        text: 'A U T U M N  /  W I N T E R   C O L L E C T I O N',
        fontFamily: 'Georgia, serif',
        fontSize: 14,
        fontWeight: 'normal',
        textAlign: 'center',
        textColor: '#e7e5e4',
        letterSpacing: 0.25,
      },
      {
        id: 'tpl-3-brand',
        name: 'Brand Name Title',
        type: 'text',
        x: 100,
        y: 200,
        width: 1000,
        height: 120,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3,
        blendMode: 'normal',
        text: 'L U M I N A I R E',
        fontFamily: 'Playfair Display, Georgia, serif',
        fontSize: 72,
        fontWeight: '400',
        textAlign: 'center',
        textColor: '#fafaf9',
        letterSpacing: 0.2,
      },
      {
        id: 'tpl-3-tagline',
        name: 'Campaign Subtitle',
        type: 'text',
        x: 200,
        y: 340,
        width: 800,
        height: 60,
        rotation: 0,
        opacity: 0.8,
        visible: true,
        locked: false,
        zIndex: 4,
        blendMode: 'normal',
        text: 'Modern Elegance Sculpted by Architectural Silhouette & Pure Silk',
        fontFamily: 'Georgia, serif',
        fontStyle: 'italic',
        fontSize: 22,
        fontWeight: '300',
        textAlign: 'center',
        textColor: '#a8a29e',
      },
      {
        id: 'tpl-3-cta',
        name: 'Callout Action',
        type: 'text',
        x: 450,
        y: 450,
        width: 300,
        height: 48,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 5,
        blendMode: 'normal',
        text: 'DISCOVER LOOKBOOK',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 13,
        fontWeight: '700',
        textAlign: 'center',
        textColor: '#0c0a09',
        letterSpacing: 0.15,
        textBackground: {
          enabled: true,
          color: '#f5f5f4',
          padding: 12,
          radius: 4,
        },
      },
    ],
  },
  {
    id: 'quote-card-minimal',
    name: 'Inspirational Quote Card',
    category: 'Creative',
    thumbnailColor: '#d97706',
    canvas: {
      width: 1080,
      height: 1080,
      bgType: 'gradient',
      bgColor: '#fffbeb',
      gradientStart: '#fffbeb',
      gradientEnd: '#fef3c7',
      gradientAngle: 180,
    },
    elements: [
      {
        id: 'tpl-4-mark',
        name: 'Quotation Mark Glyph',
        type: 'text',
        x: 120,
        y: 180,
        width: 200,
        height: 150,
        rotation: 0,
        opacity: 0.18,
        visible: true,
        locked: false,
        zIndex: 1,
        blendMode: 'normal',
        text: '“',
        fontFamily: 'Georgia, serif',
        fontSize: 200,
        fontWeight: 'bold',
        textAlign: 'left',
        textColor: '#d97706',
      },
      {
        id: 'tpl-4-quote',
        name: 'Main Quote Content',
        type: 'text',
        x: 120,
        y: 350,
        width: 840,
        height: 300,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2,
        blendMode: 'normal',
        text: '“Simplicity is about subtracting the obvious and adding the meaningful.”',
        fontFamily: 'Georgia, serif',
        fontStyle: 'italic',
        fontSize: 48,
        fontWeight: 'normal',
        textAlign: 'left',
        textColor: '#1c1917',
        lineHeight: 1.35,
      },
      {
        id: 'tpl-4-author',
        name: 'Quote Author',
        type: 'text',
        x: 120,
        y: 690,
        width: 600,
        height: 50,
        rotation: 0,
        opacity: 0.8,
        visible: true,
        locked: false,
        zIndex: 3,
        blendMode: 'normal',
        text: '— JOHN MAEDA, The Laws of Simplicity',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 20,
        fontWeight: '700',
        textAlign: 'left',
        textColor: '#78350f',
        letterSpacing: 0.08,
      },
    ],
  },
  {
    id: 'event-poster-music',
    name: 'Music Festival Poster',
    category: 'Events',
    thumbnailColor: '#7c3aed',
    canvas: {
      width: 1200,
      height: 1800,
      bgType: 'gradient',
      bgColor: '#180828',
      gradientStart: '#180828',
      gradientEnd: '#4c0519',
      gradientAngle: 170,
    },
    elements: [
      {
        id: 'tpl-5-bgcircle',
        name: 'Neon Sun',
        type: 'shape',
        shapeType: 'circle',
        x: 250,
        y: 200,
        width: 700,
        height: 700,
        rotation: 0,
        opacity: 0.7,
        visible: true,
        locked: false,
        zIndex: 1,
        blendMode: 'screen',
        fillColor: '#ec4899',
      },
      {
        id: 'tpl-5-title',
        name: 'Festival Title',
        type: 'text',
        x: 100,
        y: 750,
        width: 1000,
        height: 200,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2,
        blendMode: 'normal',
        text: 'SYNTHWAVE\nNIGHTS 2026',
        fontFamily: 'Impact, sans-serif',
        fontSize: 108,
        fontWeight: '900',
        textAlign: 'center',
        textColor: '#ffffff',
        lineHeight: 0.95,
        shadow: {
          color: '#db2777',
          blur: 40,
          offsetX: 0,
          offsetY: 0,
          opacity: 0.8,
        },
      },
      {
        id: 'tpl-5-date',
        name: 'Date and Venue',
        type: 'text',
        x: 100,
        y: 1000,
        width: 1000,
        height: 60,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3,
        blendMode: 'normal',
        text: 'OCTOBER 24-26 • METROPOLIS ARENA',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 28,
        fontWeight: '800',
        textAlign: 'center',
        textColor: '#38bdf8',
        letterSpacing: 0.15,
      },
      {
        id: 'tpl-5-artists',
        name: 'Artist Lineup',
        type: 'text',
        x: 150,
        y: 1120,
        width: 900,
        height: 220,
        rotation: 0,
        opacity: 0.85,
        visible: true,
        locked: false,
        zIndex: 4,
        blendMode: 'normal',
        text: 'THE MIDNIGHT ECHO • GUNSHIP • KAVINSKY • TIMECOP1983\nCARPENTER BRUT • PERTURBATOR • DANCE WITH THE DEAD\nPLUS 30+ LIVE VISUAL SYNTHESIZER ARTISTS',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 22,
        fontWeight: '600',
        textAlign: 'center',
        textColor: '#cbd5e1',
        lineHeight: 1.7,
      },
    ],
  },
];
